<a href="https://colab.research.google.com/github/yeonghun00/stock/blob/master/crawler/naverfinance_crawler_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime

class Stock:
  def __init__(self, code_name):
    self.code_name = code_name
    self.df = self.do_it()

  def page_to_df(self, page):
    url = "https://finance.naver.com/item/sise_day.nhn?code=" + self.code_name + "&page=" + str(page)
    result = requests.get(url)
    bs_obj = BeautifulSoup(result.content, "html.parser")
    tr = bs_obj.find_all("tr", {'onmouseover':'mouseOver(this)', 'onmouseout':"mouseOut(this)"})
    data_dict = {}
    for i in range(10):
      spans = tr[i].find_all('span')
      lines = [span.get_text() for span in spans]
      objdate = datetime.datetime.strptime(lines[0], '%Y.%m.%d')
      data_dict[objdate] = lines[1:]

    df = pd.DataFrame.from_dict(data_dict).transpose()
    df.columns = ['Close','_','Open',
                        'High','Low','Volume']
    df = df.drop(columns="_")
    return df

  def do_it(self):
    df = self.page_to_df(1)
    for i in range(2, 9999):
      try: 
        df = df.append(self.page_to_df(i))
      except:
        break
    return df.sort_index(axis = 0) 

  def get_df(self):
    return self.df

In [2]:
s = Stock('326030')

In [3]:
s.get_df()

              Close     Open     High      Low      Volume
2020-07-03  165,000  165,000  165,000  165,000     711,921
2020-07-06  214,500  214,500  214,500  193,500   7,126,211
2020-07-07  216,500  219,000  269,500  210,000  10,105,187
2020-07-08  217,000  214,500  225,000  198,000   5,990,009
2020-07-09  205,500  213,500  220,000  205,500   1,897,646
2020-07-10  205,500  200,500  213,500  198,500   1,825,361
2020-07-13  199,000  206,000  207,500  199,000   1,072,716
2020-07-14  188,500  199,500  201,500  188,000   1,389,588
2020-07-15  177,000  190,000  191,000  174,000   1,859,251
2020-07-16  183,500  179,000  197,500  179,000   3,290,169
2020-07-17  191,000  185,000  193,000  183,500   1,109,080
2020-07-20  187,000  193,500  195,000  185,000     657,860
2020-07-21  185,500  186,500  189,000  184,500     564,184
2020-07-22  188,000  192,000  205,000  188,000   2,269,779
2020-07-23  186,500  189,000  190,500  183,000     572,644
2020-07-24  189,000  184,500  194,500  183,000     806,058
2020-07-27  191,500  192,500  199,500  190,500     913,434
2020-07-28  190,000  193,000  193,500  188,000     351,351
2020-07-29  186,500  190,500  190,500  185,500     281,090
2020-07-30  185,000  187,000  189,000  183,500     318,789
2020-07-31  182,000  184,000  184,500  182,000     222,520
2020-08-03  175,000  174,000  178,000  170,000     748,436
2020-08-04  175,500  176,500  179,000  175,000     334,937
2020-08-05  179,500  177,500  183,000  175,500     508,410
2020-08-06  179,500  182,500  182,500  178,500     257,948
2020-08-07  179,000  180,000  181,000  178,000     231,477
2020-08-10  192,500  185,500  196,000  184,500   1,791,403
2020-08-11  191,500  196,000  196,500  190,000     547,133
2020-08-12  191,000  193,000  195,500  188,000     419,642
2020-08-13  186,000  192,000  193,000  184,500     491,263
2020-08-14  178,500  184,000  184,000  177,500     512,876
2020-08-18  171,000  175,000  178,000  170,500     429,385
2020-08-19  172,000  170,500  175,000  170,500     251,460
2020-08-20  167,000  171,000  174,000  165,500     321,586
2020-08-21  162,500  169,000  169,500  159,500     396,107
2020-08-24  168,000  160,000  168,500  155,000     390,851
2020-08-25  172,000  169,000  173,000  168,500     245,620
2020-08-26  172,000  174,000  175,000  171,000     198,839
2020-08-27  167,500  172,000  172,500  167,000     193,632
2020-08-28  167,000  167,500  169,000  166,500     153,232
2020-08-31  163,500  170,000  170,000  163,000     233,285
2020-09-01  171,000  165,000  173,000  163,500     388,140
2020-09-02  181,500  171,000  185,000  167,500   1,273,960
2020-09-03  182,000  183,500  186,500  179,000     564,777
2020-09-04  190,000  177,000  191,500  177,000   1,263,233
2020-09-07  191,500  193,000  193,500  187,000     588,499
2020-09-08  188,000  193,000  197,000  187,000     688,213
2020-09-09  191,000  184,500  194,000  181,000     752,071
2020-09-10  184,500  194,000  194,500  184,500   1,216,687
2020-09-11  175,000  180,500  182,500  173,000     827,865
2020-09-14  170,500  174,500  174,500  169,000     369,858
2020-09-15  171,500  172,000  173,000  170,500     213,266
2020-09-16  170,000  170,500  173,000  170,000     209,954
2020-09-17  170,500  170,000  171,500  169,000     192,071
2020-09-18  171,500  170,500  172,000  169,000     139,378
2020-09-21  167,500  171,500  172,000  165,500     210,008
2020-09-22  164,500  167,500  168,500  163,000     191,073
2020-09-23  162,000  165,000  166,500  158,500     190,137
2020-09-24  159,000  158,000  159,000  156,000     251,602
2020-09-25  158,500  159,500  161,500  158,000     131,804